/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProxyRouteImport } from './routes/proxy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as KeywordsRouteImport } from './routes/keywords'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as BigscreenRouteImport } from './routes/bigscreen'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProxyRoute = ProxyRouteImport.update({
  id: '/proxy',
  path: '/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsRoute = KeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const BigscreenRoute = BigscreenRouteImport.update({
  id: '/bigscreen',
  path: '/bigscreen',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRoute
  '/bigscreen': typeof BigscreenRoute
  '/conversations': typeof ConversationsRoute
  '/dashboard': typeof DashboardRoute
  '/keywords': typeof KeywordsRoute
  '/monitoring': typeof MonitoringRoute
  '/notifications': typeof NotificationsRoute
  '/proxy': typeof ProxyRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRoute
  '/bigscreen': typeof BigscreenRoute
  '/conversations': typeof ConversationsRoute
  '/dashboard': typeof DashboardRoute
  '/keywords': typeof KeywordsRoute
  '/monitoring': typeof MonitoringRoute
  '/notifications': typeof NotificationsRoute
  '/proxy': typeof ProxyRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRoute
  '/bigscreen': typeof BigscreenRoute
  '/conversations': typeof ConversationsRoute
  '/dashboard': typeof DashboardRoute
  '/keywords': typeof KeywordsRoute
  '/monitoring': typeof MonitoringRoute
  '/notifications': typeof NotificationsRoute
  '/proxy': typeof ProxyRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/alerts'
    | '/analysis'
    | '/bigscreen'
    | '/conversations'
    | '/dashboard'
    | '/keywords'
    | '/monitoring'
    | '/notifications'
    | '/proxy'
    | '/settings'
    | '/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/alerts'
    | '/analysis'
    | '/bigscreen'
    | '/conversations'
    | '/dashboard'
    | '/keywords'
    | '/monitoring'
    | '/notifications'
    | '/proxy'
    | '/settings'
    | '/setup'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/alerts'
    | '/analysis'
    | '/bigscreen'
    | '/conversations'
    | '/dashboard'
    | '/keywords'
    | '/monitoring'
    | '/notifications'
    | '/proxy'
    | '/settings'
    | '/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AlertsRoute: typeof AlertsRoute
  AnalysisRoute: typeof AnalysisRoute
  BigscreenRoute: typeof BigscreenRoute
  ConversationsRoute: typeof ConversationsRoute
  DashboardRoute: typeof DashboardRoute
  KeywordsRoute: typeof KeywordsRoute
  MonitoringRoute: typeof MonitoringRoute
  NotificationsRoute: typeof NotificationsRoute
  ProxyRoute: typeof ProxyRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proxy': {
      id: '/proxy'
      path: '/proxy'
      fullPath: '/proxy'
      preLoaderRoute: typeof ProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords': {
      id: '/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof KeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bigscreen': {
      id: '/bigscreen'
      path: '/bigscreen'
      fullPath: '/bigscreen'
      preLoaderRoute: typeof BigscreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AlertsRoute: AlertsRoute,
  AnalysisRoute: AnalysisRoute,
  BigscreenRoute: BigscreenRoute,
  ConversationsRoute: ConversationsRoute,
  DashboardRoute: DashboardRoute,
  KeywordsRoute: KeywordsRoute,
  MonitoringRoute: MonitoringRoute,
  NotificationsRoute: NotificationsRoute,
  ProxyRoute: ProxyRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
